version: '3'

networks:
  wan:
    external: true

services:
  c1:
    image: consul:latest
    command: consul agent -dev -client=0.0.0.0 -bind=0.0.0.0
    networks:
      wan:
        ipv4_address: 10.1.1.11
    ports:
      - "8401:8400"
      - "8501:8500"
      - "8601:8600/udp"
  c2:
    image: consul:latest
    command: consul agent -dev -client=0.0.0.0 -bind=0.0.0.0 -join=cmain
    networks:
      wan:
        ipv4_address: 10.1.1.12
    ports:
      - "8402:8400"
      - "8502:8500"
      - "8602:8600/udp"
    links:
      - c1:cmain
  c3:
    image: consul:latest
    command: consul agent -dev -client=0.0.0.0 -bind=0.0.0.0 -join=cmain
    networks:
      wan:
        ipv4_address: 10.1.1.13
    ports:
      - "8403:8400"
      - "8503:8500"
      - "8603:8600/udp"
    links:
      - c1:cmain
  bd:
    image: boatdirectory:0.1
    networks:
      wan:
        ipv4_address: 10.1.1.21
    ports:
      - "8770:8770"
  bdc:
    image: boatdirectory-client:0.1
    networks:
      wan:
        ipv4_address: 10.1.1.22
    ports:
      - "8080:8080"
