version: '3'

networks:
  wan:
    external: true

services:
  bd:
    image: boatdirectory:0.1
    networks:
      wan:
        ipv4_address: 10.1.1.21
    ports:
      - "8770:8770"
  bdc:
    image: boatdirectory-client:0.1
    networks:
      wan:
        ipv4_address: 10.1.1.22
    ports:
      - "8080:8080"
