version: '3'

networks:
  wan:
    external: true

services:
  c3:
    image: consul:latest
    command: consul agent -dev -client=0.0.0.0 -bind=0.0.0.0 -join=http://10.1.1.11:8501
    networks:
      wan:
        ipv4_address: 10.1.1.13
    ports:
      - "8403:8400"
      - "8503:8500"
      - "8603:8600/udp"
