version: '3'

networks:
  wan:
    external: true

services:
  c2:
    image: consul:latest
    command: consul agent -dev -client=10.1.1.12 -bind=10.1.1.12 -join=http://10.1.1.11:8501
    networks:
      wan:
        ipv4_address: 10.1.1.12
    ports:
      - "8402:8400"
      - "8502:8500"
      - "8602:8600/udp"
